
[general]
	"Max Distance" = 24
	"Render with Interface Disabled (F1)" = false
	"Height Above Mob" = 0.7
	"Draw Background" = false
	"Background Padding" = 0
	"Background Height" = 6
	"Health Bar Height" = 4
	"Plate Size" = 25
	"Plate Size (Boss)" = 50
	"Show Attributes" = true
	"Show Armor" = true
	"Group Armor (condense 5 iron icons into 1 diamond icon)" = true
	"Color Health Bar by Type (instead of health percentage)" = true
	"HP Text Height" = 14
	"Show Max HP" = false
	"Show Current HP" = false
	"Show HP Percentage" = false
	"Display on Players" = true
	"Display on Bosses" = true
	"Only show the health bar for the entity looked at" = true
	"Show entities with full health" = true
	"Show Debug Info with F3" = true
	#Blacklist uses entity IDs, not their display names. Use F3 to see them in the Neat bar.
	Blacklist = ["minecraft:shulker", "minecraft:armor_stand", "minecraft:cod", "minecraft:salmon", "minecraft:pufferfish", "minecraft:tropical_fish"]

