
#Common config settings
[common]
	#If true, backpack can only be worn by placing it in curios 'Back' slot
	#WARNING - Remember to TAKE OFF BACKPACK BEFORE enabling or disabling this integration!! - if not you'll lose your backpack
	curiosIntegration = false
	enableBackpackAbilities = true
	#Places backpack at place where player died
	backpackDeathPlace = true
	#Places backpack at place where player died, replacing all blocks that are breakable and do not have inventory (backpackDeathPlace must be true in order to work)
	backpackForceDeathPlace = false
	#Enables button in backpack gui, which allows to empty tank
	enableEmptyTankButton = true
	enableSleepingBagSpawnPoint = false
	#Enables backpacks spawning in loot chests
	enableLoot = true

