
["World Generation Settings"]
	#Generate boulder
	generateBoulder = true
	#Generate smooth dirt patch
	generateSmoothDirtPatch = true
	#Generate humus patch in the jungle
	generateHumusPatch = true
	#Generate clover patch
	generateCloverPatch = true
	#Generate daisies patch
	generateDaisiesPatch = true
	#Generate pebbles
	generatePebbles = true
	#Generate rock
	generateRock = true
	#Generate fallen log
	generateFallenLog = true
	#Generate daisy-decorated tree
	generateOakDaisies = true
	#Generate hollow log oak tree
	generateOakHollow = true
	#Generate fallen log
	generateFallenLogNether = true
	#Generate mushroom shelf on the surface
	generateMushroomShelfSurface = true
	#Generate mushroom shelf underground
	generateMushroomShelfUndergroundMin = true
	#Generate hanging moss 
	generateHangingMoss = true
	#Trees will spawn with a block of rooted dirt underneath, rather than regular dirt.
	generateTreeRoots = true
	#Trees in forests will spawn with 2D branch blocks.
	generateTreeBranches = true
	#Chance that fallen leaves will generate under a tree (in percentage). Set to 0 to disable this.
	#Range: 0.0 ~ 1.0
	fallenLeavesChance = 0.1
	#Dark Oak trees will spawn with a patch of humus underneath.
	generateDarkOakHumus = true

["Gameplay Settings"]
	#Mushrooms can be placed and survive regardless of light level.
	removeMushroomLightLevel = true

