#Microphone activation type
#Allowed Values: PTT, VOICE
microphone_activation_type = "PTT"
#The threshold for voice activation in dB
#Range: -127.0 ~ 0.0
voice_activation_threshold = -50.0
#The voice chat volume
#Range: 0.0 ~ 2.0
voice_chat_volume = 1.0
#The voice chat microphone amplification
#Range: 0.0 ~ 4.0
microphone_amplification = 1.0
#The size of the audio output buffer in packets
#Higher values mean a higher latency, but less crackles
#Increase this value if you have an unstable internet connection
#Range: 1 ~ 16
output_buffer_size = 5
#The maximum amount of audio packets that are held back, if a packet arrives out of order or gets dropped
#This prevents discarding audio packets that are slightly out of order
#Set this to 0 to disable
#Range: 0 ~ 16
audio_packet_threshold = 3
#The time it takes for the microphone to deactivate when using voice activation
#A value of 1 means 20 milliseconds, 2=40 ms, 3=60 ms, ...
#Range: 0 ~ 100
voice_deactivation_delay = 25
#The microphone used by the voice chat
#Empty for default device
microphone = "OpenAL Soft on Microphone (Voicemod Virtual Audio Device (WDM))"
#The speaker used by the voice chat
#Empty for default device
speaker = "OpenAL Soft on Speakers (High Definition Audio Device)"
#If the microphone is muted (only when using voice activation)
muted = false
#If the voice chat is disabled (sound and microphone off)
disabled = false
#If the voice chat icons should be hidden
hide_icons = false
#If the group HUD should be visible
show_group_hud = true
#If the own icon should be shown when in a group
show_own_group_icon = true
#The scale of the group HUD
#Range: 0.01 ~ 10.0
group_hud_icon_scale = 2.0
#The orientation of the player icons in the group HUD
#Allowed Values: VERTICAL, HORIZONTAL
group_player_icon_orientation = "VERTICAL"
#The X position of the player icons in the group HUD
#Negative values mean anchoring to the right
#Range: > -2147483648
group_player_icon_pos_x = 4
#The Y position of the player icons in the group HUD
#Negative values mean anchoring to the bottom
#Range: > -2147483648
group_player_icon_pos_y = 4
#The X position of the HUD icons
#Negative values mean anchoring to the right
#Range: > -2147483648
hud_icon_pos_x = 16
#The Y position of the HUD icons
#Negative values mean anchoring to the bottom
#Range: > -2147483648
hud_icon_pos_y = -16
#The scale of the HUD icons
#Range: 0.01 ~ 10.0
hud_icon_scale = 1.0
#The location where recordings should be saved
#Leave empty for default location
recording_destination = ""
#The quality of the recorded audio
#0 = highest quality, 9 = lowest quality
#Range: 0 ~ 9
recording_quality = 2
#If noise cancellation should be enabled
denoiser = false
#If voice chat should work in singleplayer/LAN worlds
run_local_server = true
#Whether to use the Java implementation of microphone capturing instead of OpenAL
java_microphone_implementation = false
#If the microphone workaround hack should be used (MacOS only)
macos_microphone_workaround = false
#If fake players should have the disconnected icon above their head
show_fake_players_disconnected = false
#If the volume adjustment GUI should also show offline players
offline_player_volume_adjustment = false
#The 3D audio type
#Allowed Values: NORMAL, REDUCED, OFF
audio_type = "NORMAL"
#If the mod should load native libraries
#If set to false, the Java Opus implementation will be used and the denoiser won't be available
use_natives = true

